from pack7.module_open_files import file_processing
from pack7.module_rand_int_float import rand_int_float
from pack7.module_random_names import random_name_to_file, create_random_name
from pack7.module_rename_files import rename_files